global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: athena-python-service
    static_configs:
      - targets: ["athena-python-service:8001"]
    metrics_path: /metrics

  - job_name: discovery-server
    static_configs:
      - targets: ["discovery-server:8761"]
    metrics_path: /actuator/prometheus

  - job_name: user-service
    static_configs:
      - targets: ["user-service:8081"]
    metrics_path: /actuator/prometheus

  - job_name: customer-service
    static_configs:
      - targets: ["customer-service:8082"]
    metrics_path: /actuator/prometheus

  - job_name: media-service
    static_configs:
      - targets: ["media-service:8083"]
    metrics_path: /actuator/prometheus

  - job_name: notification-service
    static_configs:
      - targets: ["notification-service:8085"]
    metrics_path: /actuator/prometheus

  - job_name: scoring-service
    static_configs:
      - targets: ["scoring-service:8080"]
    metrics_path: /actuator/prometheus

  - job_name: mlflow
    static_configs:
      - targets: ["mlflow:5000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres:9187"]

  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
